name: example
description: A new Flutter project.
version: 1.1.2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter:
    path: ../
  flutter_apns: ^1.4.1
  flutter_local_notifications: ^2.0.2
  flutter_svg: ^0.19.1
  flutter_secure_storage: ^3.3.5
  yaml: ^2.2.1
  uuid: ^2.2.2
  streaming_shared_preferences: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  test: any

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
