name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.2.5
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.10.1
  rxdart: ^0.24.1
  jiffy: ^3.0.1
  flutter_portal: ^0.1.0
  cached_network_image: ^2.2.0+1
  flutter_markdown: ^0.4.2
  url_launcher: ^5.4.11
  video_player: ^0.10.11+1
  chewie: ^0.9.10
  file_picker: ^1.12.0
  image_picker: ^0.6.7+2
  flutter_keyboard_visibility: ^3.2.1
  stream_chat: ^0.2.3
  mime: ^0.9.6+3
  visibility_detector: ^0.1.5
  http_parser: ^3.1.4

dev_dependencies:
  pedantic: ^1.9.0
