name: stream_chat_persistence_example
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  stream_chat: ^5.0.0-beta.2
  stream_chat_persistence: ^5.0.0-beta.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true