name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 4.1.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  drift: ^1.5.0
  flutter:
    sdk: flutter
  logging: ^1.0.1
  meta: ^1.3.0
  mutex: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  sqlite3_flutter_libs: ^0.5.0
  stream_chat: ^4.3.0
dev_dependencies:
  build_runner: ^2.0.1
  dart_code_metrics: ^4.4.0
  drift_dev: ^1.5.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  