name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 1.5.2
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  meta: ^1.2.4
  moor: ^3.4.0
  mutex: ^2.0.0
  path: ^1.7.0
  path_provider: ^1.6.27
  sqlite3_flutter_libs: ^0.4.0+1
  stream_chat: ^1.5.1

dev_dependencies:
  build_runner: ^1.11.0
  mockito: ^4.1.3
  moor_generator: ^3.4.1
  test: ^1.15.7
