name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 8.0.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  drift: ^2.18.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.24
  stream_chat:
    git:
      url: https://github.com/qdhayana/stream-chat-flutter.git
      ref: master
      path: packages/stream_chat

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  