name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 2.0.0-nullsafety.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  meta: ^1.3.0
  moor: ^4.2.1
  mutex: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  sqlite3_flutter_libs: ^0.4.1
  stream_chat: ^1.5.3

dev_dependencies:
  build_runner: ^2.0.1
  mocktail: ^0.1.1
  moor_generator: ^4.2.1
  pedantic: ^1.11.0
  test: ^1.16.8
