name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 1.3.2+1-beta
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: ^2.4.2
  collection: ^1.14.13
  dio: ^3.0.10
  freezed_annotation: ^0.12.0
  http_parser: ^3.1.4
  json_annotation: ^3.0.1
  logging: ^0.11.4
  meta: ^1.2.4
  mime: ^0.9.7
  rxdart: ^0.25.0
  uuid: ^2.2.2
  web_socket_channel: ^1.1.0

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.12.7
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  test: ^1.15.7