name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 3.5.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  dio: ^4.0.0
  equatable: ^2.0.0
  freezed_annotation: ^1.0.0
  http_parser: ^4.0.0
  jose: ^0.3.2
  json_annotation: ^4.3.0
  logging: ^1.0.1
  meta: ^1.3.0
  mime: ^1.0.0
  rate_limiter: ^0.1.1
  rxdart: ^0.27.0
  uuid: ^3.0.4
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.1
  dart_code_metrics: ^4.4.0
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  mocktail: ^0.2.0
  test: ^1.17.12