name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 6.8.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  dio: ^5.3.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http_parser: ^4.0.2
  jose: ^0.3.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  mime: ^1.0.4
  rate_limiter: ^1.0.0
  rxdart: ^0.27.7
  synchronized: ^3.1.0
  uuid: ">=3.0.7 <5.0.0"
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6
