name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 1.0.2-beta
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  logging: ^0.11.4
  dio: ^3.0.10
  web_socket_channel: ^1.1.0
  uuid: ^2.2.2
  async: ^2.4.2
  rxdart: ^0.25.0
  collection: ^1.14.13
  pedantic: ^1.9.2
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.15.7
  mockito: ^4.1.1
