name: stream_chat_flutter_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  stream_chat_flutter: ^6.4.0
  stream_chat_localizations: ^5.4.0
  stream_chat_persistence: ^6.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_doodle.png
