name: stream_chat_flutter_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  stream_chat_flutter: ^7.0.1
  stream_chat_localizations: ^7.0.1
  stream_chat_persistence: ^7.0.1

dependency_overrides:
  stream_chat:
    path: ../../stream_chat
  stream_chat_flutter:
    path: ..
  stream_chat_flutter_core:
    path: ../../stream_chat_flutter_core
  stream_chat_localizations:
    path: ../../stream_chat_localizations
  stream_chat_persistence:
    path: ../../stream_chat_persistence

flutter:
  uses-material-design: true
  assets:
    - assets/background_doodle.png
