name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 7.2.0-hotfix.1
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  collection: ^1.17.2
  connectivity_plus: ">=4.0.2 <7.0.0"
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  meta: ^1.9.1
  rxdart: ^0.27.7
  stream_chat: ^7.2.0-hotfix.1

dev_dependencies:
  build_runner: ^2.4.6
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mocktail: ^1.0.0

