name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 2.0.0-nullsafety.6
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  connectivity_plus: ^1.0.1
  flutter:
    sdk: flutter
  meta: ^1.3.0
  rxdart: ^0.27.0
  stream_chat: ^2.0.0-nullsafety.6

dependency_overrides:
  stream_chat:
    path: ../stream_chat

dev_dependencies:
  fake_async: ^1.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.3

