name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 8.1.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  internet_connection_checker_plus: ^2.5.1
  meta: ^1.9.1
  rxdart: ^0.28.0
  stream_chat:
    git:
      url: https://github.com/qdhayana/stream-chat-flutter.git
      ref: master
      path: packages/stream_chat

dev_dependencies:
  build_runner: ^2.4.9
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mocktail: ^1.0.0

