name: stream_chat_localizations
description: The Official localizations for Stream Chat Flutter, a service for building chat applications
version: 7.2.0-hotfix.1
homepage: https://github.com/GetStream/stream-chat-flutter
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stream_chat_flutter:
    path: ../stream_chat_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: stream_chat_localizations
      ios:
        default_package: stream_chat_localizations
      windows:
        default_package: stream_chat_localizations
      linux:
        default_package: stream_chat_localizations
      macos:
        default_package: stream_chat_localizations
      web:
        default_package: stream_chat_localizations
