name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 6.12.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cached_network_image: ^3.2.3
  chewie: ^1.7.0
  collection: ^1.17.1
  contextmenu: ^3.0.0
  dart_vlc: ^0.4.0
  desktop_drop: ^0.4.1
  diacritic: ^0.1.4
  dio: ^5.3.2
  ezanimation: ^0.6.0
  file_picker: ^5.3.3
  file_selector: ^1.0.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17+1
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.7
  http_parser: ^4.0.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.2
  jiffy: ^6.2.1
  lottie: ^2.6.0
  meta: ^1.9.1
  path_provider: ^2.1.0
  photo_manager: ^2.7.1
  photo_view: ^0.14.0
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  shimmer: ^3.0.0
  # stream_chat_flutter_core: ^6.11.0
  stream_chat_flutter_core:
    git: 
      url: https://github.com/Intune-Communications-LTD/stream-chat-flutter.git
      path: packages/stream_chat_flutter_core
      ref: app_customizations
  synchronized: ^3.1.0
  thumblr: ^0.0.4
  url_launcher: ^6.1.12
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3

flutter:
  plugin:
    platforms:
      android:
        default_package: stream_chat_flutter
      ios:
        default_package: stream_chat_flutter
      windows:
        default_package: stream_chat_flutter
      linux:
        default_package: stream_chat_flutter
      macos:
        default_package: stream_chat_flutter
      web:
        default_package: stream_chat_flutter

  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.0
  path: ^1.8.3