name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 1.1.0-beta
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter_core: ^1.1.0-beta
  flutter_app_badger: ^1.1.2
  photo_view: ^0.10.3
  rxdart: ^0.25.0
  scrollable_positioned_list: ^0.1.8
  jiffy: ^3.0.1
  flutter_svg: ^0.19.1
  flutter_portal: ^0.3.0
  cached_network_image: ^2.5.0
  shimmer: ^1.1.2
  flutter_markdown: ^0.5.2
  url_launcher: ^5.7.10
  emojis: ^0.9.3
  video_player: ^1.0.1
  chewie: ^0.12.1+1
  file_picker: ^2.1.5
  image_picker: ^0.6.7+17
  flutter_keyboard_visibility: ^4.0.2
  video_compress: ^2.1.1
  visibility_detector: ^0.1.5
  http_parser: ^3.1.4
  meta: ^1.2.4
  lottie: ^0.7.0+1
  substring_highlight: ^0.1.2
  flutter_slidable: ^0.5.7
  clipboard: ^0.1.2+8
  image_gallery_saver: ^1.6.7
  esys_flutter_share: ^1.0.2
  photo_manager: ^0.6.0
  transparent_image: ^1.0.0
  ezanimation: ^0.4.1
  synchronized: ^2.2.0+2
  characters: ^1.0.0
  dio: ^3.0.10
  path_provider: ^1.6.27
  video_thumbnail: ^0.2.5+1

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2