name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 2.0.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.0.0
  characters: ^1.1.0
  chewie: ^1.2.0
  collection: ^1.15.0
  dio: ^4.0.0
  ezanimation: ^0.5.0
  file_picker: ^3.0.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.0.1
  flutter_markdown: ^0.6.1
  flutter_portal: ^0.4.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  http_parser: ^4.0.0
  image_gallery_saver: ^1.6.9
  image_picker: ^0.8.2
  jiffy: ^4.1.0
  lottie: ^1.0.1
  meta: ^1.3.0
  path_provider: ^2.0.1
  photo_manager: ^1.1.6
  photo_view: ^0.12.0
  rxdart: ^0.27.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share_plus: ^2.0.3
  shimmer: ^2.0.0
  stream_chat_flutter_core: ^2.0.0
  substring_highlight: ^1.0.26
  synchronized: ^3.0.0
  url_launcher: ^6.0.3
  video_compress: ^3.0.0
  video_player: ^2.1.0
  video_thumbnail: ^0.3.3
  visibility_detector: ^0.2.0

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  mocktail: ^0.1.2
  pedantic: ^1.11.0

